apiVersion: v1
kind: Service
metadata:
  name: grafana-ext1
  namespace: kube-prometheus-stack
spec:
  loadBalancerClass: kube-vip.io/kube-vip-class
  ports:
  - nodePort: <node port>
    port: <service port>
    protocol: TCP
    targetPort: <Service target port>
  selector:
    app.kubernetes.io/name: <specify service label>
  type: LoadBalancer
  loadBalancerIP: "<specify ip address>"
